export const NFT_CONFIG = {
  singular_graphql_endpoint: "https://gql-rmrk2-prod.graphcdn.app",
  singular_fee: 0.035,
  proofofchaos_scores_endpoint: "https://scores.proofofchaos.app/shelf/nfts",
  proofofchaos_graphql_endpoint:
    "https://squid.subsquid.io/referenda-dashboard/v/v2/graphql",
  polkassembly_graphql_endpoint: "https://kusama.polkassembly.io/v1/graphql",
  singular_referendum_collections: [
    "3208723ec6f65df810-ITEM",
    "3208723ec6f65df810-ITEMXEVRLOOT",
    "3208723ec6f65df810-ITEMXRMRK",
    "3208723ec6f65df810-ITEMXMT",
    "3208723ec6f65df810-ITEMXPUNKS",
    "3208723ec6f65df810-ITEMXARCHIVERSE",
    "3208723ec6f65df810-BITS",
  ],
  referendum_rarities: ["common", "rare", "epic", "legendary"],
  quizzes: {
    229: [
      {
        question: "What is the name of ref 223 parachain?",
        answers: ["Polkadot", "Kusama", "Karura", "Ethereum"],
        multiple: "true",
      },
      {
        question: "What is the name of Polkadot's founder?",
        answers: ["Wavin Good", "Mavin Wood", "Gavin Wood"],
      },
    ],
  },
  classic_referendums: [
    {
      ref: "Referendum 214",
      thumb: "bafybeifamwhsxcospc3dd36bzmwl7ju7wvcbm5zduuwozrwduiiaxclssq",
      amount: "131",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+214",
      symbol: "214QCC",
      description:
        "'Quartz Crystal Cluster'\n\nIn Referendum 214 the community voted on whether to force-update the Quartz runtime. It had gotten stuck during a runtime upgrade and stopped producing blocks.\n\nArtist: @kseniashikh\n\n",
    },
    {
      ref: "Referendum 214",
      thumb: "bafybeibovgnwe2nkudiibpty5rmglhvsqz7zyzlnau2l2h3cqg4ybuhbo4",
      amount: "220",
      artist: "LokiKot(@LokiPages)",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+214",
      symbol: "214PQ",
      description:
        "'Pure Quartz'\n\nIn Referendum 214 the community voted on whether to force-update the Quartz runtime. It had gotten stuck during a runtime upgrade and stopped producing blocks.\n\nArtist: LokiKot(@LokiPages)\n\n",
    },
    {
      ref: "Referendum 214",
      thumb: "bafybeief3by4inyfri4bry2nnjzcriv4upur35ea6cwlzlludsl2i5mufu",
      amount: "1187",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+214",
      symbol: "214MQ",
      description:
        "'Milky Quartz'\n\nIn Referendum 214 the community voted on whether to force-update the Quartz runtime. It had gotten stuck during a runtime upgrade and stopped producing blocks.\n\nArtist: @kseniashikh\n\n",
    },
    {
      ref: "Referendum 213",
      thumb: "bafybeieszreuez7hag6llvctgdpu2nqgp2eclkpjd2erhentmuevu4owyu",
      amount: "202",
      artist: "LokiKot(@LokiPages)",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+213",
      symbol: "213MBB",
      description:
        "'Modern Ballot Box'\n\nIn Referendum 213 the community voted on whether to upgrade the Kusama runtime to version 0.9.25. The upgrade includes several changes in preparation for Governance 2.0.\n\nArtist: LokiKot(@LokiPages)\n\n",
    },
    {
      ref: "Referendum 213",
      thumb: "bafybeichjsekkqvhduh3vykkvsafhgrpo4uvkhnfaah5y2chjl4cdtoesu",
      amount: "136",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+213",
      symbol: "213HBB",
      description:
        "'Historic Ballot Box'\n\nIn Referendum 213 the community voted on whether to upgrade the Kusama runtime to version 0.9.25. The upgrade includes several changes in preparation for Governance 2.0.\n\nArtist: @kseniashikh\n\n",
    },
    {
      ref: "Referendum 213",
      thumb: "bafybeiaxvb6amme7654masg2goqv5kj5fqbd6dzspbiueup4xduwsypvpq",
      amount: "1204",
      artist: "LokiKot(@LokiPages)",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+213",
      symbol: "213CBBX",
      description:
        "'Cardboard Ballot Box'\n\nIn Referendum 213 the community voted on whether to upgrade the Kusama runtime to version 0.9.25. The upgrade includes several changes in preparation for Governance 2.0.\n\nArtist: LokiKot(@LokiPages)\n\n",
    },
    {
      ref: "Referendum 211",
      thumb: "bafybeif42ddtapmdh6zv6ncofxp57dzipbciuopiewsdzygkkpk42mpd3e",
      amount: "239",
      artist: "LokiKot(@LokiPages)",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+211",
      symbol: "211TSP",
      description:
        "In Referendum 211 the community voted on whether to reset the Pichiu Parachain in order to fix bugs. The underlying proposal of this Referendum has also been replaced by Referendum 205. Since Referendum 205 has passed community vote already, this Referendum (like Referendum 209) was superfluous too.",
      title: "Trilogy Silver Piglets",
    },
    {
      ref: "Referendum 211",
      thumb: "bafybeidvzcruxyy72oywalzppxwd7enbyr3in4dnhbk2gx5b7mo6dhdswm",
      amount: "121",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+211",
      symbol: "211TGM",
      description:
        "In Referendum 211 the community voted on whether to reset the Pichiu Parachain in order to fix bugs. The underlying proposal of this Referendum has also been replaced by Referendum 205. Since Referendum 205 has passed community vote already, this Referendum (like Referendum 209) was superfluous too.",
      title: "Trilogy Gold Monkeys",
    },
    {
      ref: "Referendum 211",
      thumb: "bafybeib2sksolck3suvcvhyhndohqk63xnffml6rhth23goqwyc74h2alu",
      amount: "1079",
      artist: "LokiKot(@LokiPages)",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+211",
      symbol: "211TBM",
      description:
        "In Referendum 211 the community voted on whether to reset the Pichiu Parachain in order to fix bugs. The underlying proposal of this Referendum has also been replaced by Referendum 205. Since Referendum 205 has passed community vote already, this Referendum (like Referendum 209) was superfluous too.",
      title: "Trilogy Bronze Mice",
    },
    {
      ref: "Referendum 210",
      thumb: "bafybeiabfjqf76itpsgslclf6n5gos3dshfapi5coe3roppjk5ih3ghps4",
      amount: "156",
      artist: "LokiKot(@LokiPages)",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+210",
      symbol: "210EB",
      description:
        "In Referendum 210 the community voted on whether to upgrade the Kusama runtime to version 0.9.23. The updated code brings about several NFT related changes.",
      title: "Enchanted Book",
    },
    {
      ref: "Referendum 210",
      thumb: "bafybeibm5kik4js4axsx6bicrshsr3rgasy72fg5jvnu6vkeljmie7fdjy",
      amount: "1116",
      artist: "LokiKot(@LokiPages)",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+210",
      symbol: "210CH",
      description:
        "In Referendum 210 the community voted on whether to upgrade the Kusama runtime to version 0.9.23. The updated code brings about several NFT related changes.",
      title: "Card Holder",
    },
    {
      ref: "Referendum 210",
      thumb: "bafybeiel7kycf566nawz2v2vzn4z7hkllskkeh3x75dsfswc2uuucy24sm",
      amount: "216",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+210",
      symbol: "210CA",
      description:
        "In Referendum 210 the community voted on whether to upgrade the Kusama runtime to version 0.9.23. The updated code brings about several NFT related changes.",
      title: "Collection Album",
    },
    {
      ref: "Referendum 209",
      thumb: "bafybeiennxaxf6tx3meer5ozzmuxdirwx37t3slqrihrgcvsfyke3r2gma",
      amount: "1147",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+209",
      symbol: "209ST",
      description:
        "In Referendum 209 the community voted on whether to reset the Pichiu Parachain in order to fix bugs. The underlying proposal of this Referendum has been replaced by Referendum 205. Since Referendum 205 has passed community vote already, this Referendum was superfluous.",
      title: "Stamp",
    },
    {
      ref: "Referendum 209",
      thumb: "bafybeicdh3yvzc7mhz75ebzpcjwq44runwykgqfixxmy7kgg7vjuxs5dam",
      amount: "145",
      artist: "LokiKot(@LokiPages)",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+209",
      symbol: "209PT",
      description:
        "In Referendum 209 the community voted on whether to reset the Pichiu Parachain in order to fix bugs. The underlying proposal of this Referendum has been replaced by Referendum 205. Since Referendum 205 has passed community vote already, this Referendum was superfluous.",
      title: "Parrot",
    },
    {
      ref: "Referendum 209",
      thumb: "bafybeifhf64ysj5rlyqxemtjjldegwvchhg33hxws4licwh6iwzppy2hvu",
      amount: "203",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+209",
      symbol: "209CP",
      description:
        "In Referendum 209 the community voted on whether to reset the Pichiu Parachain in order to fix bugs. The underlying proposal of this Referendum has been replaced by Referendum 205. Since Referendum 205 has passed community vote already, this Referendum was superfluous.",
      title: "Cassette Player",
    },
    {
      ref: "Referendum 208",
      thumb: "bafybeib4oqddoicegou7rmzjzbgqicqsqqycfwnwreydmny27c656kzkqy",
      amount: "127",
      artist: "LokiKot(@LokiPages)",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXPUNKS?search=Referendum+208",
      symbol: "208MSM",
      description:
        "In Referendum 208 the community voted on whether to lower the number of nomination pools to 64 and the members per pool to 16.\n\nThis NFT can be equipped onto both the [Shelf](https://singular.app/collections/3208723ec6f65df810-SHELF) and [RMRK Punks](https://singular.app/collections/3629a3ff458d113e25-PUNK).",
      title: "Madagascan Sunset Moth",
    },
    {
      ref: "Referendum 208",
      thumb: "bafybeiagx2pzn5pucgnylj23wifzzjp4khlmiauuv7yhnnpn62vyvhy22u",
      amount: "1153",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXPUNKS?search=Referendum+208",
      symbol: "208MBM",
      description:
        "In Referendum 208 the community voted on whether to lower the number of nomination pools to 64 and the members per pool to 16.\n\nThis NFT can be equipped onto both the [Shelf](https://singular.app/collections/3208723ec6f65df810-SHELF) and [RMRK Punks](https://singular.app/collections/3629a3ff458d113e25-PUNK).",
      title: "Menelaus Blue Morpho",
    },
    {
      ref: "Referendum 208",
      thumb: "bafybeigjstdvrfngiirw3jpja2yppg5mfxzzqsnqugh5teaq3z4bew5zri",
      amount: "188",
      artist: "LokiKot(@LokiPages)",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXPUNKS?search=Referendum+208",
      symbol: "208ES",
      description:
        "In Referendum 208 the community voted on whether to lower the number of nomination pools to 64 and the members per pool to 16.\n\nThis NFT can be equipped onto both the [Shelf](https://singular.app/collections/3208723ec6f65df810-SHELF) and [RMRK Punks](https://singular.app/collections/3629a3ff458d113e25-PUNK).",
      title: "Emerald Swallowtail",
    },
    {
      ref: "Referendum 207",
      thumb: "bafybeia4z2cqq7hopgqehq5iolrtpq425f4tfnzxhy3txaez3mjfpwytfi",
      amount: "209",
      artist: "@kseniashikh",
      rarity: "legendary",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+207",
      symbol: "207CR",
      description:
        "In Referendum 207 the community voted on whether to open a HRMP channel between Robonomics and Statemine.",
      title: "Cute Robot with Music",
    },
    {
      ref: "Referendum 207",
      thumb: "bafybeidl2pefllitmxdregvcxg3pzo7oqrh7v2a75flg4ojty5ukuh27si",
      amount: "209",
      artist: "LokiKot(@LokiPages)",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+207",
      symbol: "207VR",
      description:
        "In Referendum 207 the community voted on whether to open a HRMP channel between Robonomics and Statemine.",
      title: "Vintage Robot",
    },
    {
      ref: "Referendum 207",
      thumb: "bafybeicmqlqkxb6ljmklcdoyakuiheeowv22w5seibu2czrgqps5khzxve",
      amount: "159",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+207",
      symbol: "207FR",
      description:
        "In Referendum 207 the community voted on whether to open a HRMP channel between Robonomics and Statemine.",
      title: "Futuristic Robot",
    },
    {
      ref: "Referendum 207",
      thumb: "bafybeidseydteahwveuv2q4m5dbuci6avv7fvnpuk24zlvr45zher63rai",
      amount: "1119",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+207",
      symbol: "207CR",
      description:
        "In Referendum 207 the community voted on whether to open a HRMP channel between Robonomics and Statemine.",
      title: "Cute Robot",
    },
    {
      ref: "Referendum 206",
      thumb: "bafybeicwdmev33ddehq6pmlbgvknggzyhgzmnxclzshvldj77fahntwqcu",
      amount: "114",
      artist: "Ruben from MushroomTopia",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXMT?search=Referendum+206",
      symbol: "206SB",
      description:
        "In Referendum 206 the community voted on whether to upgrade the Kusama runtime to version 0.9.23.\n\nThis NFT can be equipped onto both the [Shelf](https://singular.app/collections/3208723ec6f65df810-SHELF) and [Mirrors of Mushroom Topia](https://singular.app/collections/c8d5ea648c93514667-MTPIAMRRS).",
      title: "Starberry",
    },
    {
      ref: "Referendum 206",
      thumb: "bafybeibo6xp6x7psfzyjhdvkvqskrlybmfn67ctcjrys4jeeivg4kdxzky",
      amount: "157",
      artist: "Ruben from MushroomTopia",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXMT?search=Referendum+206",
      symbol: "206RB",
      description:
        "In Referendum 206 the community voted on whether to upgrade the Kusama runtime to version 0.9.23.\n\nThis NFT can be equipped onto both the [Shelf](https://singular.app/collections/3208723ec6f65df810-SHELF) and [Mirrors of Mushroom Topia](https://singular.app/collections/c8d5ea648c93514667-MTPIAMRRS).",
      title: "Ripeberry",
    },
    {
      ref: "Referendum 206",
      thumb: "bafkreicjw6xfltsxdttrcqbq7xltumlyz7em4spbzfl4p45762g7j4rpwm",
      amount: "1163",
      artist: "Ruben from MushroomTopia",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXMT?search=Referendum+206",
      symbol: "206BB",
      description:
        "In Referendum 206 the community voted on whether to upgrade the Kusama runtime to version 0.9.23.\n\nThis NFT can be equipped onto both the [Shelf](https://singular.app/collections/3208723ec6f65df810-SHELF) and [Mirrors of Mushroom Topia](https://singular.app/collections/c8d5ea648c93514667-MTPIAMRRS).",
      title: "Brightberry",
    },
    {
      ref: "Referendum 205",
      thumb: "bafybeiahy65ehuhily4m3qc2n2hbsgct3ixa6ggytc5wcjh6o2fbze2ecu",
      amount: "1170",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+205",
      symbol: "205SW",
      description:
        "In Referendum 205 the community voted on whether to reset the Pichiu Parachain in order to fix bugs.",
      title: "Sun Warrior",
    },
    {
      ref: "Referendum 205",
      thumb: "bafybeiehkpixwwmbes5nm2kgetwfll2yougzkvbbvqo55s5brp7c2wx7lm",
      amount: "209",
      artist: "LokiKot(@LokiPages)",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+205",
      symbol: "205SP",
      description:
        "In Referendum 205 the community voted on whether to reset the Pichiu Parachain in order to fix bugs.",
      title: "Sun Priest",
    },
    {
      ref: "Referendum 205",
      thumb: "bafybeidcoyud5syvhxl3vapsoj7er3q2sdgak56sn7bwh5ib3ye6lbldcm",
      amount: "126",
      artist: "LokiKot(@LokiPages)",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+205",
      symbol: "205SG",
      description:
        "In Referendum 205 the community voted on whether to reset the Pichiu Parachain in order to fix bugs.",
      title: "Sun God",
    },
    {
      ref: "Referendum 204",
      thumb: "bafybeicvlvgejh6wfgccb7i2wjwav6j72ulti7jyoht3z64gpsp7vlafei",
      amount: "1192",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+204",
      symbol: "204RL",
      description:
        "In Referendum 204 the community voted on whether to open a HRMP channel between Statemine and Shiden Network.",
      title: "Railroad Lamp",
    },
    {
      ref: "Referendum 204",
      thumb: "bafybeierhjjypwpr4adrutvyb5aqxfz5k6vej7tern7lfwpg2g6kursxtq",
      amount: "141",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+204",
      symbol: "204PB",
      description:
        "In Referendum 204 the community voted on whether to open a HRMP channel between Statemine and Shiden Network.",
      title: "Plasma Ball",
    },
    {
      ref: "Referendum 204",
      thumb: "bafkreiammehvsffpgjetr5pb27skfkwzy7btcsmugxhiuculrisjv7fu3q",
      amount: "175",
      artist: "LokiKot(@LokiPages)",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+204",
      symbol: "204JL",
      description:
        "'Jacob's Ladder'\n\nIn Referendum 204 the community voted on whether to open a HRMP channel between Statemine and Shiden Network.\n\nArtist: LokiKot(@LokiPages)\n\n",
    },
    {
      ref: "Referendum 203",
      thumb: "bafybeidqzyffhua7i4anes6ryx7kf5kgmvw735pqjwqaue6slgxw5oa734",
      amount: "95",
      artist: "LokiKot(@LokiPages)",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+203",
      symbol: "203LCAT",
      description:
        "In Referendum 203 the community voted (again) on whether to give the RMRK token suffiency on Statemine. The last 2 motions on the topic did not execute correctly. The third time is the charm.",
      title: "Lucky Cat",
    },
    {
      ref: "Referendum 203",
      thumb: "bafybeidxgnysjjmnshz422z3rhb5ppghvacefmlhv2ijhse7mwpwmsueji",
      amount: "690",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+203",
      symbol: "203HS",
      description:
        "In Referendum 203 the community voted (again) on whether to give the RMRK token suffiency on Statemine. The last 2 motions on the topic did not execute correctly. The third time is the charm.",
      title: "Horseshoe",
    },
    {
      ref: "Referendum 203",
      thumb: "bafybeiff2zjg75qk7sqvpui3s3m45z5ct7lns6ulrqcxbfl73cr4rsufk4",
      amount: "154",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+203",
      symbol: "203CLVR",
      description:
        "In Referendum 203 the community voted (again) on whether to give the RMRK token suffiency on Statemine. The last 2 motions on the topic did not execute correctly. The third time is the charm.",
      title: "Clover Leaf",
    },
    {
      ref: "Referendum 202",
      thumb: "bafybeic6etto7yuu23pxq3hft4uned7oxlvy5ltib4xb5retsoh4zj56zq",
      amount: "195",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+202",
      symbol: "202RING",
      description:
        "In Referendum 202 the community voted on whether to upgrade the Kusama runtime to version 0.9.22. Among other things, the new release also adds nomination pools to the Kusama Network.",
      title: "Ring",
    },
    {
      ref: "Referendum 202",
      thumb: "bafybeieu37vuf5k35eoc7fi75qhpxadhho7zqvvm3uyb6bzefpyzqypure",
      amount: "125",
      artist: "LokiKot(@LokiPages)",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+202",
      symbol: "202FLGO",
      description:
        "In Referendum 202 the community voted on whether to upgrade the Kusama runtime to version 0.9.22. Among other things, the new release also adds nomination pools to the Kusama Network.",
      title: "Flamingo",
    },
    {
      ref: "Referendum 202",
      thumb: "bafybeiemtmaz2jeqsbylkyobdrqmi64lj4fomxgslze5jkldupsijytu2m",
      amount: "1132",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+202",
      symbol: "202BALL",
      description:
        "In Referendum 202 the community voted on whether to upgrade the Kusama runtime to version 0.9.22. Among other things, the new release also adds nomination pools to the Kusama Network.",
      title: "Ball",
    },
    {
      ref: "Referendum 201",
      thumb: "bafybeihmjsphjqdwizio55yw4w5dszml4c2bfv23ukesnfjeuqj6hhrpzi",
      amount: "131",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+201",
      symbol: "201SSC",
      description:
        "In Referendum 201 the community voted on whether to make the 'Expect Chaos' on-chain remark.",
      title: "Scorpion Spider Conch",
    },
    {
      ref: "Referendum 201",
      thumb: "bafybeibm5hfunp7ozssn5okrubtbephopumztlirudy4k4t6iz44xx6v3u",
      amount: "1128",
      artist: "LokiKot(@LokiPages)",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+201",
      symbol: "201SJ",
      description:
        "In Referendum 201 the community voted on whether to make the 'Expect Chaos' on-chain remark.",
      title: "Shell Jar",
    },
    {
      ref: "Referendum 201",
      thumb: "bafybeiglchkoj44ljtafztnpt263xexx55cjv6sqpt5ldngnzqgh7itqgi",
      amount: "200",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+201",
      symbol: "201SB",
      description:
        "In Referendum 201 the community voted on whether to make the 'Expect Chaos' on-chain remark.",
      title: "Scotch Bonnet",
    },
    {
      ref: "Referendum 200",
      thumb: "bafybeid4ghgz6f27givkex6qhstlfyhzszp6yse7c6j3kw53lt7ciymrie",
      amount: "128",
      artist: "LokiKot(@LokiPages)",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+200",
      symbol: "200FB",
      description:
        "In Referendum 200 the community voted on whether to update Dora Factory's parachain in order to fix some bugs.",
      title: "Futuristic Bike",
    },
    {
      ref: "Referendum 200",
      thumb: "bafybeianeebwc4mcbmwzbm5gxifkdvsa7cu6elw6o7azwrlde47nsollnu",
      amount: "991",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+200",
      symbol: "200DB",
      description:
        "In Referendum 200 the community voted on whether to update Dora Factory's parachain in order to fix some bugs.",
      title: "Dirt Bike",
    },
    {
      ref: "Referendum 200",
      thumb: "bafybeidnlhj2qzuyiz3ncveflcszkv4sget4ri6czxrotvvmniicohb47u",
      amount: "175",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+200",
      symbol: "200CHOP",
      description:
        "In Referendum 200 the community voted on whether to update Dora Factory's parachain in order to fix some bugs.",
      title: "Chopper",
    },
    {
      ref: "Referendum 199",
      thumb: "bafybeibvlrfhjwc3hkcjplgid666yezfamekdeeo7dq5rt3rqyztdvud54",
      amount: "528",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+199",
      symbol: "199SN",
      description:
        "In Referendum 199 the community voted on whether to let Shiden swap their lease from parachain ID 2007 to ID 2120.",
      title: "Simple Necklace",
    },
    {
      ref: "Referendum 199",
      thumb: "bafybeiatgxchtgkdgr26rswbsirwuqyxqtlj4rrqmz5ifjrem4txaf3jfq",
      amount: "107",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+199",
      symbol: "199PN",
      description:
        "In Referendum 199 the community voted on whether to let Shiden swap their lease from parachain ID 2007 to ID 2120.",
      title: "Pendant Necklace",
    },
    {
      ref: "Referendum 199",
      thumb: "bafybeigjh7tgvtcldwqmr6h3vw3yqq2joliygswsr2fnxwpod4m6x77lui",
      amount: "86",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+199",
      symbol: "199MPN",
      description:
        "In Referendum 199 the community voted on whether to let Shiden swap their lease from parachain ID 2007 to ID 2120.",
      title: "Multi-Pendant Necklace",
    },
    {
      ref: "Referendum 198",
      thumb: "bafybeihmtzzpj637n336wst5fwweaeewjdhpn75guaf4xm37u5w4ddtb64",
      amount: "172",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+198",
      symbol: "198STF",
      description:
        "In Referendum 198 the community voted on whether to give Karura a 22k KSM subsidy to improve liquidity on their DeFi Platform.",
      title: "Stone Fountain",
    },
    {
      ref: "Referendum 198",
      thumb: "bafybeicc3qgbjk45kwr744x6742o6proozhj4we2laha7c2g724eio67ce",
      amount: "1010",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+198",
      symbol: "198SF",
      description:
        "In Referendum 198 the community voted on whether to give Karura a 22k KSM subsidy to improve liquidity on their DeFi Platform.",
      title: "Simple Fountain",
    },
    {
      ref: "Referendum 198",
      thumb: "bafybeiaiaoxheqetoylv7pej442jnn5taw3uew4akmppwsbxteztpfcwmy",
      amount: "117",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+198",
      symbol: "198BF",
      description:
        "In Referendum 198 the community voted on whether to give Karura a 22k KSM subsidy to improve liquidity on their DeFi Platform.",
      title: "Bird Fountain",
    },
    {
      ref: "Referendum 197",
      thumb: "bafybeidmdla2iq4emdnrt5wttkmbdz6lep3x6uvgqlbr5d6lk6p7sqb7s4",
      amount: "173",
      artist: "Elizaveta Sokolova",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+197",
      symbol: "197MBAG",
      description:
        "In Referendum 197 the community voted on whether to give the USDT token suffiency on Statemine.",
      title: "Money Bag",
    },
    {
      ref: "Referendum 197",
      thumb: "bafybeiflirzbgimydggvzpchyfujjbdi4wiskcyd2onghaw7qymjdq2cyi",
      amount: "945",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+197",
      symbol: "197COIN",
      description:
        "In Referendum 197 the community voted on whether to give the USDT token suffiency on Statemine.",
      title: "Coins",
    },
    {
      ref: "Referendum 197",
      thumb: "bafybeidekf3hzxhpbb3fhmaqabzm57t7eogkoqisdp66y37uqvbatxjedi",
      amount: "116",
      artist: "@LokiPages",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+197",
      symbol: "197CHEST",
      description:
        "In Referendum 197 the community voted on whether to give the USDT token suffiency on Statemine.",
      title: "Chest",
    },
    {
      ref: "Referendum 196",
      thumb: "bafybeigalmspsvcb3lxva2a3oqmkit2jb6h3ehujljyw75mgvsxdvt3dpy",
      amount: "120",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+196",
      symbol: "196TPOLE",
      description:
        "In Referendum 196 the community voted on whether to open a HRMP channel between Parallel Heiko and Statemine (2nd attempt after Referendum 188 did not pass). This would allow the two parachains to communicate with one another.",
      title: "Telegraph Pole",
    },
    {
      ref: "Referendum 196",
      thumb: "bafybeid7m5xxtcln5d7zcvn73arkgw3lw4ye5j4rqnaeonmtkwsayagjk4",
      amount: "927",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+196",
      symbol: "196SPTEL",
      description:
        "In Referendum 196 the community voted on whether to open a HRMP channel between Parallel Heiko and Statemine (2nd attempt after Referendum 188 did not pass). This would allow the two parachains to communicate with one another.",
      title: "Sound-Powered Telephone",
    },
    {
      ref: "Referendum 196",
      thumb: "bafybeidvniwmvx7uqffivxqygdmpcnie27pbg7uunldb2s7ret43dc32w4",
      amount: "151",
      artist: "@LokiPages",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+196",
      symbol: "196CBSW",
      description:
        "In Referendum 196 the community voted on whether to open a HRMP channel between Parallel Heiko and Statemine (2nd attempt after Referendum 188 did not pass). This would allow the two parachains to communicate with one another.",
      title: "Crossbar Switch",
    },
    {
      ref: "Referendum 195",
      thumb: "bafybeihszt4thy36teqkorurn2f4kj64hf2os57spflny3o2ztilfxzew4",
      amount: "98",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+195",
      symbol: "195RBIRD",
      description:
        "In Referendum 195 the community voted on whether to upgrade the Kusama runtime to version 0.9.20. Among other things the new code also improves parachain block times.\n\nArtist: Elizaveta Sokolova",
      title: "Robot Bird",
    },
    {
      ref: "Referendum 195",
      thumb: "bafkreihuakdytsejju3ktfix3kji2wxfrk7xmaerjpmncxy6deajqcsnle",
      amount: "133",
      artist: "@LokiPages",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+195",
      symbol: "195BRBIRD",
      description:
        "In Referendum 195 the community voted on whether to upgrade the Kusama runtime to version 0.9.20. Among other things the new code also improves parachain block times.\n\nArtist: LokiKot(@LokiPages)",
      title: "Brick Bird",
    },
    {
      ref: "Referendum 195",
      thumb: "bafybeievk3cfedhomlqv4yov6lei345ai4zlyfchlh2q2gnwatpav7z5va",
      amount: "929",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+195",
      symbol: "195BBIRD",
      description:
        "In Referendum 195 the community voted on whether to upgrade the Kusama runtime to version 0.9.20. Among other things the new code also improves parachain block times.\n\nArtist: @kseniashikh",
      title: "Block Bird",
    },
    {
      ref: "Referendum 194",
      thumb: "bafkreiepehhxo7lgy4aie7xnwm6j3x3u5tt5zfg54jkis7z66guextau4y",
      amount: "104",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+194",
      symbol: "194TMTR",
      description:
        "In Referendum 194 the community voted on whether to let Moonriver and Khala extend their leases by swapping parachain 2112 with 2023 and 2111 with 2004 respectively.\n\nArtist: @kseniashikh",
      title: "Time-Turner",
    },
    {
      ref: "Referendum 194",
      thumb: "bafybeic5jg4ubggtxv6c25gppda7h4gkivkvy2k5ezlz7k2blgr645lj4a",
      amount: "153",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+194",
      symbol: "194HGLASS",
      description:
        "In Referendum 194 the community voted on whether to let Moonriver and Khala extend their leases by swapping parachain 2112 with 2023 and 2111 with 2004 respectively.\n\nArtist: @kseniashikh",
      title: "Hourglass",
    },
    {
      ref: "Referendum 194",
      thumb: "bafkreifehtxivpxxia5d2aqnhoxh3kbx6vb43xfgg73cgvfynnw2nkfre4",
      amount: "932",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+194",
      symbol: "194CARD",
      description:
        "In Referendum 194 the community voted on whether to let Moonriver and Khala extend their leases by swapping parachain 2112 with 2023 and 2111 with 2004 respectively.\n\nArtist: @kseniashikh",
      title: "Card",
    },
    {
      ref: "Referendum 193",
      thumb: "bafybeif7pz6c5tkzbwivcxqhhto52vvxdbwnubloup3ieqhdf6ukconqwa",
      amount: "174",
      artist: "@LokiPages",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXRMRK?search=Referendum+193",
      symbol: "193RMRKTS",
      description:
        "In Referendum 193 the community voted on whether to give the RMRK token suffiency on Statemine.\n\nArtist: LokiKot(@LokiPages)",
      title: "RMRK Token Silver",
    },
    {
      ref: "Referendum 193",
      thumb: "bafybeibzfdbwbrsmspqtsr4hffylp7qu6biujlwwrtav4xvp5i24dlasjq",
      amount: "159",
      artist: "@LokiPages",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXRMRK?search=Referendum+193",
      symbol: "193RMRKTG",
      description:
        "In Referendum 193 the community voted on whether to give the RMRK token suffiency on Statemine.\n\nArtist: LokiKot(@LokiPages)",
      title: "RMRK Token Gold",
    },
    {
      ref: "Referendum 193",
      thumb: "bafybeiarj5oqgb6zfvnbxir6hk5msun3ice5uhizhfnmevncsignmh4vom",
      amount: "1118",
      artist: "@LokiPages",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXRMRK?search=Referendum+193",
      symbol: "193RMRKTB",
      description:
        "In Referendum 193 the community voted on whether to give the RMRK token suffiency on Statemine.\n\nArtist: LokiKot(@LokiPages)",
      title: "RMRK Token Bronze",
    },
    {
      ref: "Referendum 193",
      thumb: "bafybeics4c24rh5bxtuglo36pejb77cwyw2oyqkrv2wd5nqop7jzjfnchy",
      amount: "111",
      artist: "RMRK Art Team",
      rarity: "legendary",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXRMRK?search=Referendum+193",
      symbol: "193BABD",
      description:
        "In Referendum 193 the community voted on whether to give the RMRK token suffiency on Statemine.\n\nArtist: RMRK Art Team",
      title: "Babushka Doll",
    },
    {
      ref: "Referendum 192",
      thumb: "bafybeihi75mlqiglhoc5eczmjotk2nw7c5ve6eimjalrmf2egdqfjd6xp4",
      amount: "112",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+192",
      symbol: "192PHX",
      description:
        "In Referendum 192 the community voted on whether to let Karura extend its lease by swapping parachain 2003 with parachain 2000.\n\nArtist: @kseniashikh",
      title: "Phoenix",
      thumbs: [
        "ipfs://ipfs/bafybeihi75mlqiglhoc5eczmjotk2nw7c5ve6eimjalrmf2egdqfjd6xp4",
        "ipfs://ipfs/bafybeidos56y3jdg5e2fcvvsndwqnljowg3hjmr4uruc2uqo4isrsvbzeq",
      ],
    },
    {
      ref: "Referendum 192",
      thumb: "bafybeifxy657n53cn5tzxynawdpb6su336riibatvhm2kgqpnstxduicxq",
      amount: "152",
      artist: "@kseniashikh",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+192",
      symbol: "192HEGG",
      description:
        "In Referendum 192 the community voted on whether to let Karura extend its lease by swapping parachain 2003 with parachain 2000.\n\nArtist: @kseniashikh",
      title: "Hatched Egg",
      thumbs: [
        "ipfs://ipfs/bafybeigigf2h6yykkpw4jhjwxe5u2doyfx3hfymtmekp6naxoc4ltqjvgm",
        "ipfs://ipfs/bafybeifxy657n53cn5tzxynawdpb6su336riibatvhm2kgqpnstxduicxq",
      ],
    },
    {
      ref: "Referendum 192",
      thumb: "bafkreiguo4jnn2l3zmlscbmk3ogwho2ldx6rmvge76pospoay25xa44m2e",
      amount: "1066",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+192",
      symbol: "192EGG",
      description:
        "In Referendum 192 the community voted on whether to let Karura extend its lease by swapping parachain 2003 with parachain 2000.",
      title: "Egg",
      thumbs: [
        "ipfs://ipfs/bafkreiguo4jnn2l3zmlscbmk3ogwho2ldx6rmvge76pospoay25xa44m2e",
        "ipfs://ipfs/bafkreifwnvlkgzx43qgs57ydu255ezk2koajmp5r5l6syj46tsvozqy5uq",
      ],
    },
    {
      ref: "Referendum 192",
      thumb: "bafybeibs3rz2o4bidw5uuz6ljgurknobheeycdwaszmpnpypuaewhuiesq",
      amount: "100",
      artist: "@kseniashikh",
      rarity: "legendary",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+192",
      symbol: "192EGG",
      description:
        "Take good care of your adolescent dragon to make it grow big and strong.",
      title: "Adolescent Dragon: Equippable on Shelf",
      thumbs: [
        "ipfs://ipfs/bafybeiel3v7hvpgjjwmanbyd35e3lqq4znwfgfdhvyobrxpw6ikvdgebne",
        "ipfs://ipfs/bafybeid55ev7qfoqp2umyy6kwfhtsckvhdncp6gwctmubfouvv6x7ju3b4",
        "ipfs://ipfs/bafybeihqlsluf2vx7jjc5rvsmjjn5jiwidcfw3ktg6orv4dvhqfhdtofgm",
        "ipfs://ipfs/bafybeialnxxdqnyvl6lr3mr7ftkj5w7lfdrkeqze6txcd5dfhfbqkbtiyy",
        "ipfs://ipfs/bafybeibs3rz2o4bidw5uuz6ljgurknobheeycdwaszmpnpypuaewhuiesq",
        "ipfs://ipfs/bafybeidlvs7ddbt3oco5apldq5iasy74bwukry2zbyma65bdvzikokkaiu",
      ],
    },
    {
      ref: "Referendum 191",
      thumb: "bafybeigfhpkiltenly7y27db5fhiecldwf4qcqwf4jjbhlv4s3dbjbdl24",
      amount: "1057",
      artist: "Elizaveta Sokolova",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+191",
      description:
        "In Referendum 191 the community voted on whether to upgrade the Statemine Runtime to v900.\n\nArtist: Elizaveta Sokolova",
      title: "Gerbera",
      resources: [
        "ipfs://ipfs/bafkreidhokvlvgwdb6dylr7xssivtiwifoqzfa2hwvezgzzg5p2uztzx6y",
        "ipfs://ipfs/bafkreidjtxqzmytnwrcskpetzomjx3ytsaopr72ybq3coqgngp2ywqliou",
      ],
    },
    {
      ref: "Referendum 191",
      thumb: "bafybeic6gx7d3p46l5ia7qkqffb5vwm25ilhdsf5zttbzcbg25kme3g5ty",
      amount: "190",
      artist: "Elizaveta Sokolova",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+191",
      description:
        "In Referendum 191 the community voted on whether to upgrade the Statemine Runtime to v900.",
      title: "Lemon Tree",
      resources: [
        "ipfs://ipfs/bafkreicwvwkivw7telv7rtovi64fyiip7sx32m56kgsf6sj7xdqpvipa7i",
        "ipfs://ipfs/bafkreig45zyz22eydwdeq3ybsrmvbl3gqriksalcfhbawi5pc25fb5w7yy",
      ],
    },
    {
      ref: "Referendum 191",
      thumb: "bafybeihntv3fsu2bbhie5z5k2r25ebcvsmsuku23rz2ijezpbyyingkq6i",
      amount: "116",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+191",
      description:
        "In Referendum 191 the community voted on whether to upgrade the Statemine Runtime to v900.",
      title: "Bamboo",
      resources: [
        "ipfs://ipfs/bafkreib6l27ggi5gmi4lddbqmq2w7k25f4vsijmvb4zld5ueh4u3h2e3ue",
        "ipfs://ipfs/bafkreigp7mjbbg53dzvzetx7wr2b3hwwx4rm53hfipuaanht3cb5fi4vsm",
      ],
    },
    {
      ref: "Referendum 190",
      thumb: "bafybeici2z3xdzbt6rjuxfobbcye6nujjgxz4vq5d2sxclxygjsc4hxqqi",
      amount: "634",
      artist: "@kseniashikh",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+190",
      description:
        "In Referendum 190 the community voted on whether Parallel Heiko would be reimbursed the 63 KSM they have lost.",
      title: "Sign",
      resources: [
        "ipfs://ipfs/bafkreia5hjaag5uyld4xbsteuqp6bk4stazzce4gkybjs23lt4ywhyfmue",
        "ipfs://ipfs/bafkreigybqlvu5cvu7p636f74hcprbkead6unqzdmppkoe25yby4p4vh7q",
      ],
      thumbs: [
        "ipfs://ipfs/bafybeici2z3xdzbt6rjuxfobbcye6nujjgxz4vq5d2sxclxygjsc4hxqqi",
      ],
    },
    {
      ref: "Referendum 190",
      thumb: "bafybeievujt5ablv3pgpruyf75k3gttqh2yrsey2qxz32eoo4omoqoscze",
      amount: "225",
      artist: "@LokiPages",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+190",
      description:
        "In Referendum 190 the community voted on whether Parallel Heiko would be reimbursed the 63 KSM they have lost.",
      title: "Piggy Bank",
      resources: [
        "ipfs://ipfs/bafkreiadsqfadkevsteflmnurbcgjj3kxjwveeddmoftvnzb2hdsjiubdu",
        "ipfs://ipfs/bafkreiee2cex65ir2uxi7d2xosypy54m5e4yd7khuk3p6a3avcb63trlcq",
      ],
      thumbs: [
        "ipfs://ipfs/bafybeievujt5ablv3pgpruyf75k3gttqh2yrsey2qxz32eoo4omoqoscze",
      ],
    },
    {
      ref: "Referendum 190",
      thumb: "bafybeiamkgjzmou654kbakdvvw6vrmgqwqcts45fryqyjeuz3glt3o2lre",
      amount: "107",
      artist: "@kseniashikh",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+190",
      description:
        "In Referendum 190 the community voted on whether Parallel Heiko would be reimbursed the 63 KSM they have lost.",
      title: "Voucher",
      resources: [
        "ipfs://ipfs/bafkreicjzflbx6uxhnvviaztj4zkubs6b46dj7j3ohsm2gncip6klruaja",
        "ipfs://ipfs/bafkreidwtopquqnch2lfo3wrburtlzpxx7vql2m66ksqjhfuuzznob7pdu",
      ],
      thumbs: [
        "ipfs://ipfs/bafybeiamkgjzmou654kbakdvvw6vrmgqwqcts45fryqyjeuz3glt3o2lre",
      ],
    },
    {
      ref: "Referendum 189",
      thumb: "bafybeidzrofjbzolluwkf5px3wa4zq3ol5arpkeyfjwddyyuicopkwmrp4",
      amount: "759",
      artist: "Elizaveta Sokolova",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+189",
      description:
        "In Referendum 189 the community voted on whether to upgrade the Kusama runtime to version 0.9.19.",
      title: "Squeaky Chaos #189",
      resources: [
        "ipfs://ipfs/bafkreicqvb26fajmlq23gsnmee7lkd2g62ovf3l5ugws3hhargqpjaxag4",
        "ipfs://ipfs/bafkreifh5lfpe4mizthtgwlsqw6v4ad2srvti5s6wzflweo6gf34qccjum",
      ],
    },
    {
      ref: "Referendum 189",
      thumb: "bafybeih27n7uacw4tu75ipddg22iqmdl7enu446bzzvnl24lci3ehw6dwq",
      amount: "130",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+189",
      description:
        "In Referendum 189 the community voted on whether to upgrade the Kusama runtime to version 0.9.19.",
      title: "Chaos #189",
      resources: [
        "ipfs://ipfs/bafkreib7ea6lsjepebgkfnyjebkze4nwcqn2vhy3ytzfepsxhluyhjdkla",
        "ipfs://ipfs/bafkreiey5rntu7snlzqkxphxlb4pacpuvqkvbmos6v7z7rgg62zn6zhwui",
      ],
    },
    {
      ref: "Referendum 188",
      thumb: "bafybeibh42ljkqxrdktn6ix5afmdajvpnfkrjdsc4wriv7v7hgwdvaznqi",
      amount: "583",
      artist: "Elizaveta Sokolova",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+188",
      description:
        "In Referendum 188 the community voted on whether to open a HRMP channel between Parallel Heiko and Statemine. This would allow the two parachains to communicate with one another.",
      title: "Tin Can Telephone",
      resources: [
        "ipfs://ipfs/bafkreihsinemgxkykkatgjs5k5mf4ffrvkyhzoojunm7knll6pr3sobik4",
        "ipfs://ipfs/bafkreiee25xtptpye64cmdix4e6eji7g7illctfjn6dfhkigdfh4g5qz3u",
        "ipfs://ipfs/bafkreihs6xwrqai47ejgurdmkzmq3pkll34axfqxftpcxfo6fumbewepey",
      ],
      thumbs: [
        "ipfs://ipfs/bafybeibh42ljkqxrdktn6ix5afmdajvpnfkrjdsc4wriv7v7hgwdvaznqi",
      ],
    },
    {
      ref: "Referendum 188",
      thumb: "bafybeidzcbwwsoue6zdmkyliieskwhvlokrfqf5mk2esabspolmzaweqnm",
      amount: "214",
      artist: "Elizaveta Sokolova",
      rarity: "rare",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+188",
      description:
        "In Referendum 188 the community voted on whether to open a HRMP channel between Parallel Heiko and Statemine. This would allow the two parachains to communicate with one another.",
      title: "Telephone",
      resources: [
        "ipfs://ipfs/bafkreiaod2gf4udm2gkuxxwft6uix4euquhosahisajsioxo6zl2aqtnnu",
        "ipfs://ipfs/bafkreic6qryohs6zhketwmyt5i5dquohcn5fuzqs4a4jpusozelof4smqq",
      ],
      thumbs: [
        "ipfs://ipfs/bafybeidzcbwwsoue6zdmkyliieskwhvlokrfqf5mk2esabspolmzaweqnm",
      ],
    },
    {
      ref: "Referendum 188",
      thumb: "bafybeif6viqhk7n5mqvhjqv4hude2lxfvqudrw6dmrfp5sd3obo3v2lr54",
      amount: "123",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+188",
      description:
        "In Referendum 188 the community voted on whether to open a HRMP channel between Parallel Heiko and Statemine. This would allow the two parachains to communicate with one another.",
      title: "Tin Can Telephone Statue",
      resources: [
        "ipfs://ipfs/bafkreic4xgewxed3m3umaiyjvfga37jo4dpdqh7iedimbsnarns6n5n2ce",
        "ipfs://ipfs/bafkreihs6xwrqai47ejgurdmkzmq3pkll34axfqxftpcxfo6fumbewepey",
      ],
      thumbs: [
        "ipfs://ipfs/bafybeif6viqhk7n5mqvhjqv4hude2lxfvqudrw6dmrfp5sd3obo3v2lr54",
      ],
    },
    {
      ref: "Referendum 187",
      thumb: "bafybeiaeetqjklrdpcq2dudk6ut5h6rmy2mqx5vosxwawzgxz2avelzw4y",
      amount: "784",
      artist: "Elizaveta Sokolova",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXEVRLOOT?search=Referendum+187",
      description:
        "In Referendum 187 the community voted on whether to upgrade the Encointer runtime to full functionality. As a common good parachain Encointer stands for promoting fairness and economic growth for everyone.",
      title: "Vase",
      resources: [
        "ipfs://ipfs/bafkreigg23xc5ojlaih4xwpj6owszpsviyc77zkdkhzzolbqn3o2bnq3aq",
        "ipfs://ipfs/bafkreigjpgbtqcnp3dd2mik63hhckzl4j7shfho4ljzfarqbi3ko33qc5u",
      ],
    },
    {
      ref: "Referendum 187",
      thumb: "bafybeiaxgs6vos3ik7ckrjkd6ory5v2zat6mz56taplfldozv644uq2f4q",
      amount: "101",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEMXEVRLOOT?search=Referendum+187",
      description:
        "In Referendum 187 the community voted on whether to upgrade the Encointer runtime to full functionality. As a common good parachain Encointer stands for promoting fairness and economic growth for everyone.",
      title: "Fist",
      resources: [
        "ipfs://ipfs/bafkreib6bu3js2h74zoppue7ntymprvy2vjtiugjbq4ijvvprfzfaihecy",
        "ipfs://ipfs/bafkreiepfo5zhobcyxkfqzx42lzoabmzh6qqo63bqxdeqzzknrtt2ra3oy",
      ],
    },
    {
      ref: "Referendum 186",
      thumb: "bafybeihmyylrlxqwrjo4v6bwd25ll7ue54nvg4mlifwqlqr7y2h6zwtbty",
      amount: "778",
      artist: "Elizaveta Sokolova",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+186",
      description:
        "In Referendum 186 the community voted on whether Zug (German: train) will be leaving the Council Station.",
      title: "Toy Train",
      resources: [
        "ipfs://ipfs/bafkreigmne26i3jgev5pompsbfq5nnxoi5m2g3ep6rrrnpkxblucjbo6ea",
        "ipfs://ipfs/bafkreih25d6eode7qhif623qsecuwgm4xf7ydwrtslicqeno3mdflikwie",
      ],
    },
    {
      ref: "Referendum 186",
      thumb: "bafybeifpbj34mk267t5b4pez2dzuzzuuqigfmwa7pcvw6si4h63n3iy63u",
      amount: "119",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+186",
      description:
        "In Referendum 186 the community voted on whether Zug (German: train) will be leaving the Council Station.",
      title: "Model Train",
      resources: [
        "ipfs://ipfs/bafkreidybo5cnqpaswftxtirexiau6u7hzkuqiwbcjunw3mvmjtn276amq",
        "ipfs://ipfs/bafkreihjwlk5z2b2wuirmg4k6k6d3gpehzyf7pdebphtmelygrsu5x6bgu",
      ],
    },
    {
      ref: "Referendum 185",
      thumb: "bafybeibjeuesqwtazypxgz57mngn7eoueqwx44ygg7bsdmjqiynvi2eroy",
      amount: "741",
      artist: "Elizaveta Sokolova",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+185",
      description:
        "In Referendum 185 the community voted on whether to update the genesis state of the Mangata X chain.",
      title: "Themis",
      resources: [
        "ipfs://ipfs/bafkreib4h2ua3jyqt5qied5tt6usqfcnozpjygexd4hnzx4cpn6glebqza",
        "ipfs://ipfs/bafkreibg2avnv6mxzrwvwwqxfwftxgfyggna2s5deahaul7gel4p4rt4oe",
      ],
    },
    {
      ref: "Referendum 185",
      thumb: "bafybeie7mjp6mjcnuqf22oe53er6puj2disgiyl2orgsccdu4udtal2wxu",
      amount: "145",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+185",
      description:
        "In Referendum 185 the community voted on whether to update the genesis state of the Mangata X chain.",
      title: "Airwhale",
      resources: [
        "ipfs://ipfs/bafkreicw4wipplacu4jl2d3apx2jqnc6ti5um3g2mxqld47oci6atbxzxq",
        "ipfs://ipfs/bafkreievc5py655bueag4na37czvbyhkb4a7ic3wxfhmeu4xh3qvcb7w5m",
      ],
    },
    {
      ref: "Referendum 184",
      thumb: "bafybeifzec7ukrspyriej3vswmr3h5pxjsdtdthnfrb5rqua3vs7irhuba",
      amount: "662",
      artist: "Elizaveta Sokolova",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+184",
      description:
        "The Statemine parachain is well rooted within the Kusama ecosystem. In Referendum 184 the community voted on whether to upgrade its runtime to v800, fixing a bug on the chain.",
      title: "Cactus v800",
      resources: [
        "ipfs://ipfs/bafkreibwkdk5qkamjuvq35mnkiq2caatznzxbq42gnygjls43h6iyld7gm",
        "ipfs://ipfs/bafkreihgtdpg3fgvwhwwsdzpewtv2hu3mqek2bk2bmnwsbo3ufgpjiyr3i",
      ],
    },
    {
      ref: "Referendum 184",
      thumb: "bafybeiareevlsfclespslg6if6u2xkew4zq34mdperxj2yhprzxxbp6yae",
      amount: "141",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+184",
      description:
        "The Statemine parachain is well rooted within the Kusama ecosystem. In Referendum 184 the community voted on whether to upgrade its runtime to v800, fixing a bug on the chain.",
      title: "Bonsai v800",
      resources: [
        "ipfs://ipfs/bafkreigfhhe4yphpcclz2udcml3wbplypdv5vsq67f2uyflodvxirvqbw4",
        "ipfs://ipfs/bafkreihmcqxe4hxqdxme3hbumf6e4nchjl5axnb2thizxayrc3ugpawcju",
      ],
    },
    {
      ref: "Referendum 183",
      thumb: "bafybeicotw5kj3swhghoog2y6of4ppayrmenyxacqjrs3boczyw4qndcl4",
      amount: "519",
      artist: "Elizaveta Sokolova",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+183",
      description: "The duck comes floating around for runtime upgrades.",
      title: "Squeaky Chaos #183",
      resources: [
        "ipfs://ipfs/bafkreiffyg5ideshujr7jr7stpy3ihzlm6pxsuwtdbjg5p5amcgs3n32em",
        "ipfs://ipfs/bafkreifxtcbea5j4u7gojh4jmoceby6sf2iugavetrrjjxrmhpmqi6cjb4",
      ],
    },
    {
      ref: "Referendum 183",
      thumb: "bafybeibidsw5kvf2zzdmnk5vctadizay7om6u4q6hv3uhmeem74huakp6q",
      amount: "164",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+183",
      description: "The canary comes flying in for runtime upgrades.",
      title: "Chaos #183",
      resources: [
        "ipfs://ipfs/bafkreiha3roq5pudz2wtwpwnu6kgkfkr2k2jfgucqkuxmhduv3lghugdh4",
        "ipfs://ipfs/bafkreihu6j2snww2p23x5syi72g564rofmqvnr57hryo2nuh2s6ph36vqe",
      ],
    },
    {
      ref: "Referendum 182",
      thumb: "bafybeibmbknwfm4gnsnc6qud2p35djzmwspm2ytd3x22pyjvl3cc6umpzq",
      amount: "500",
      artist: "Elizaveta Sokolova",
      rarity: "common",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+182",
      description:
        "A memory of the time when the whole community voted on giving council member Jam a verified identity.",
      title: "Photo Frame",
      resources: [
        "ipfs://ipfs/bafkreiate4dnegpkmxs654r7b3fn4xnhuujneo63qq4d2zchivnfxxdrsy",
        "ipfs://ipfs/bafkreidkbr4jfyptdmvoolleq2jmgxc34hyrwgtgc6gxnz2vmcz22xzr7u",
      ],
    },
    {
      ref: "Referendum 182",
      thumb: "bafybeiabqlwschsszffrku6t5x7rk4cd2ldil7ryywnybb5zneoeqqr32q",
      amount: "170",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+182",
      description:
        "A memory of the time when the whole community voted on giving council member Jam a verified identity.",
      title: "Jam Jar",
      resources: [
        "ipfs://ipfs/bafkreiawrf4e4goywwzdvv4xcjhg2hwgfga6jnsusbucamjgoxzdwop2yq",
        "ipfs://ipfs/bafkreidrgq4lbe5sfws3hdjto766btptuhwowaeniktjzmgigxyziv6m7u",
      ],
    },
    {
      ref: "Referendum 181",
      thumb: "bafybeifvo6wc5zkjuc3gc4zk6feg5wyuws7b2emxflg4reabxm2mmnn7aa",
      amount: "476",
      artist: "Elizaveta Sokolova",
      rarity: "epic",
      url: "https://singular.app/collections/3208723ec6f65df810-ITEM?search=Referendum+181",
      description: "The very first item to add to your shelf.",
      title: "Trophy",
      resources: [
        "ipfs://ipfs/bafkreif2lkmgjftunw22o4hrtmurw4mn7yfkoh62k7ifhmino5fwwhpysi",
        "ipfs://ipfs/bafkreighma3o3hbjhya2otemmptldvq46zhmfk6z2wry2xceqxyw6pf7we",
      ],
    },
  ],
};
